.TH "fa_logger" 3 "Sun Sep 23 2018" "PJ01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
fa_logger
.SH SYNOPSIS
.br
.PP
.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBFA_Logger\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
@package fa_logger
Logging function for PJ01, see PJ01.pdf for project spec. Order of opertaions:
    Set the file names
    Remove any previou files if they exists
    Create the .log file
    Create the .txt file

.fi
.PP
 
.SH "Author"
.PP 
Generated automatically by Doxygen for PJ01 from the source code\&.
