.TH "delta" 3 "Sun Sep 23 2018" "PJ01" \" -*- nroff -*-
.ad l
.nh
.SH NAME
delta
.SH SYNOPSIS
.br
.PP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "def \fB__init__\fP (self, \fBdelta\fP)"
.br
.RI "Init the data in Transitions\&. "
.in -1c
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "\fBcurrent_state\fP"
.br
.RI "'Current state' of transition function "
.ti -1c
.RI "\fBsymbol\fP"
.br
.RI "'Symbol' of transition function "
.ti -1c
.RI "\fBnext_state\fP"
.br
.RI "'Next state' of transition function "
.in -1c
.SH "Detailed Description"
.PP 

.PP
.nf
Plain-old-data holder for a transition given byour in file.  Only sets and gets its data

.fi
.PP
 
.SH "Constructor & Destructor Documentation"
.PP 
.SS "def __init__ ( self,  delta)"

.PP
Init the data in Transitions\&. 
.PP
\fBParameters:\fP
.RS 4
\fIself\fP pointer to self 
.br
\fIdelta\fP tuple of transition table values (current state, symbol, to state) 
.RE
.PP


.SH "Author"
.PP 
Generated automatically by Doxygen for PJ01 from the source code\&.
